site_name: 'EshopByRaduz'

nav:
  - Home: index.md
  - Arch:
    - Dictionary.md 
    - TOGAF:
      - Motivation: 
        - TOGAF/Motivation/Motivation.md 
        - Stakeholders: 
            - TOGAF/Motivation/Stakeholders/BusinessOwner.md
            - TOGAF/Motivation/Stakeholders/Marketing.md
            - TOGAF/Motivation/Stakeholders/Management.md
            - TOGAF/Motivation/Stakeholders/Operations.md
            - TOGAF/Motivation/Stakeholders/Finance.md
            - TOGAF/Motivation/Stakeholders/Compliance.md
            - TOGAF/Motivation/Stakeholders/IT.md
            - TOGAF/Motivation/Stakeholders/Customer.md
            - TOGAF/Motivation/Stakeholders/POs.md
        - TOGAF/Motivation/Impact.md 
      - Business:
        - TOGAF/Business/DomainStakeholder.md
        - TOGAF/Business/Raci.md
        - TOGAF/Business/WebVitals.md
        - Domény: 
          - TOGAF/Business/Domains.md
          - Product:
            - TOGAF/Business/Domains/Product/Product.md
            - TOGAF/Business/Domains/Product/Dictionary.md
          - Procurement:
            - TOGAF/Business/Domains/Procurement/Procurement.md
            - TOGAF/Business/Domains/Procurement/Dictionary.md
          - Stock: 
            - TOGAF/Business/Domains/Stock/Stock.md
            - TOGAF/Business/Domains/Stock/Dictionary.md
            - Funkce: 
              - TOGAF/Business/Domains/Stock/ItemCreation.md
          - Accounting:
            - TOGAF/Business/Domains/Accounting/Accounting.md
            - TOGAF/Business/Domains/Accounting/Dictionary.md
          - Regulatory:
            - TOGAF/Business/Domains/Regulatory/Regulatory.md
            - TOGAF/Business/Domains/Regulatory/Dictionary.md
          - Pricing:
            - TOGAF/Business/Domains/Pricing/Pricing.md
            - TOGAF/Business/Domains/Pricing/Dictionary.md
          - Catalog:
            - TOGAF/Business/Domains/Catalog/Catalog.md
            - TOGAF/Business/Domains/Catalog/Dictionary.md
          - Customer:
            - TOGAF/Business/Domains/Customer/Customer.md
            - TOGAF/Business/Domains/Customer/Dictionary.md
          - Provisioning:
            - TOGAF/Business/Domains/Provisioning/Provisioning.md
            - TOGAF/Business/Domains/Provisioning/Dictionary.md
          - Search:
            - TOGAF/Business/Domains/Search/Search.md
            - TOGAF/Business/Domains/Search/Dictionary.md
          - Marketing:
            - TOGAF/Business/Domains/Marketing/Marketing.md
            - TOGAF/Business/Domains/Marketing/Dictionary.md
          - Basket:
            - TOGAF/Business/Domains/Basket/Basket.md
            - TOGAF/Business/Domains/Basket/Dictionary.md
          - Checkout:
            - TOGAF/Business/Domains/Checkout/Checkout.md
            - TOGAF/Business/Domains/Checkout/Dictionary.md
          - Order:
            - TOGAF/Business/Domains/Order/Order.md
            - TOGAF/Business/Domains/Order/Dictionary.md
          - Payments:
            - TOGAF/Business/Domains/Payments/Payments.md
            - TOGAF/Business/Domains/Payments/Dictionary.md
          - Shipping:
            - TOGAF/Business/Domains/Shipping/Shipping.md
            - TOGAF/Business/Domains/Shipping/Dictionary.md
          - Fulfillment:
            - TOGAF/Business/Domains/Fulfillment/Fulfillment.md
            - TOGAF/Business/Domains/Fulfillment/Dictionary.md
          - Claims:
            - TOGAF/Business/Domains/Claims/Claims.md
            - TOGAF/Business/Domains/Claims/Dictionary.md
        - Procesy: 
            - TOGAF/Business/Flows/Purchase.md
      - Application:
        - Domény:
          - Stock:
            - TOGAF/Application/Stock/Stock.md
            - TOGAF/Application/Stock/CreateItem.md
      - Technology:
        - Domény:
          - Stock:
            - TOGAF/Technology/Stock.md

    - ADR:
      - ADR/ADRs.md
      - ADR/ADR_00001.md
      - ADR/ADR_00002.md
      - ADR/ADR_00003.md
      - ADR/ADR_00004.md
      - ADR/ADR_00005.md
      - ADR/ADR_00006.md
      - ADR/ADR_00007.md
      - ADR/ADR_00008.md
      - ADR/ADR_00009.md
      - ADR/ADR_00010.md
      - ADR/ADR_00011.md
      - ADR/ADR_00012.md
      - ADR/ADR_00013.md
      - ADR/ADR_00014.md
      - ADR/ADR_00015.md
      - ADR/ADR_00016.md
      - ADR/ADR_00017.md
      - ADR/ADR_00018.md
      - ADR/ADR_00019.md
      - ADR/ADR_00020.md
      - ADR/ADR_00021.md
      - ADR/ADR_00022.md
      - ADR/ADR_00023.md
      - ADR/ADR_00024.md
      - ADR/ADR_00025.md
      - ADR/ADR_00026.md
    - Under stress:
      - UnderStress/Stock.md
    - Automatizace:
      - Automation/Automation.md
      - Automation/CICD/Cicd.md
      - Automation/Eia.md
    - Testování:
      - Tests/Tests.md
    - Platforma:
      - Platform/Platform.md
    - Dopad:
      - Impact/Impact.md
      - Impact/Performance.md

plugins:
  - search
  - codeinclude
  - mermaid2
  - glightbox
  - charts
  - git-revision-date-localized: 
      fallback_to_build_date: true
  - drawio:
      viewer_js: "https://viewer.diagrams.net/js/viewer.min.js"    

theme:
  name: 'material'
  logo: 'logo.png'
  palette:
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  features:
    - diagrams
    - navigation.top
    - navigation.tabs
    - footer.only_login
    - navigation.instant
    - navigation.tracking
    - content.tabs.link

markdown_extensions:
  - admonition
  - toc
  - fenced_code
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
          - name: vegalite
            class: vegalite
            format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite

extra_css: 
  - styles/custom.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js'
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

